# Generated by Django 2.2.14 on 2022-03-08 21:04

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', cloudinary.models.CloudinaryField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', cloudinary.models.CloudinaryField(max_length=255)),
                ('chapters', models.ManyToManyField(blank=True, to='courses.Chapter')),
                ('levels', models.ManyToManyField(blank=True, to='courses.Level')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
    ]
